server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: infosys-search
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: tourEvent
          content-type: application/json
search:
  elasticsearch-uri: http://ec2-18-141-8-244.ap-southeast-1.compute.amazonaws.com:9200
  username: admin
  password: Moscow2008_

