server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    client:
      client-id: infosysBackend
      client-secret: p4l4Wi7a
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token/
      user-info-uri: http://localhost:8082/user/
      
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 
    url: jdbc:h2:mem:infosysdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
  application:
    name: infosys-destination
  servlet:
    multipart:
     enabled: true
     max-file-size: 100MB
     max-request-size: 1000MB


