dist: xenial
language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - satria.prayoga@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis --no-document
- sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=infosysApp-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
env:
  global:
  - secure: SjKhKG7ozRVirsAci4RM/cSs7Xpf2C5QKdToNfibpTvBl1kLv/9vnWKbPbOylFzPADCLwPKdVpE4Qp7idFIYM+7kFUwatLV6z/Vk3bVIQGfFFDNi3kJmG9uTErQnHSzz3u/s8PaaX70tbXqHKLuTvDZ3NHNQJrSp5vXG3niowcykgtP8XqqVugqbQspsWntU2LbR609zF1MmR/r/ulNGVEgQqgJ1u8CePtk4UIXThnUcqi6N+45dFgLOE73csTw9B8KTnLgmGKcobZqdr5zOmw2pJyIkvXygfEV49J+WWAmdlFqDScOsg2kzzCclSlVA1mHCsYP2vzYo/G3l9MSj2zEPLptpuyZSUtYE1mNhDHYtS84cw/fJmLSmOIL1J8Lqwb8q+S1ykhqpnaerzYuGh3PS7p9MKglUu5Gri8UsO+WZuT4QQBacf0yxdnEzReDjCei1gv6uT0jwE65/v/uIyFW+hMe80EPdBrpNl7uPaSANuGNU/fN9u3VrCw2mHLsxjZI4sYKqmActO48BF4+MGMmBwvAX3OZMuDQX9jCZa7NPM1bqG0w2dJqaW5onGfa7/8LvKrqXRE2Fhkb5RJwuoMxJraNrrBy0tCGfshjqv5lxLhty/sKezdiy9l/FCWA3dBISuQNTtGYYodWlWnubEwlhJe4mZbdczS8s5uLfkxU=
  - secure: DowmCr1HDgkPqy6GuD7z4H5V6JuKi5lm8WHs0OqMbLQyagylvKi7lqaCFw+8P+HnDWDKf6IfYD9/m/UwKdcNeTOMK6vAzmDV3WzfaPAhMgrthZeDrGyzdgbHVa+pj284gBDSiREbEBN2kl010p5aVHCTmtD5+DwsQ0JjCiQTpfhQZelKi8IPJUcekhYzcDXulysP2vtsltIB2r8+laQHIpx+e5lxx4GkxyT54bXxplAmt1oBl4+JokOAwrL1kczclyOe98YxhkJ745dgcm4fHLTth0uf7g9sXBamf3dNCRjQeXiVWjhUKZFcTbYTUEjPqVOWyoN5RzNJvpGmUJh9viwRoMxlhScSPjTZCZgdrjUwz9jmo3w1qgLnBDMEKYxIeWMCSnHZseloshujNt/GVe0Dm68EnlZPcuTNwUZGRK48DfNWpztDBT7sxhQ2ssjqRZq+5eC4U0gZStnN0fT0EMThFVU/WBtalgA86L/8nORe7+n2CoUL6ZF8D3xKyeRyiUcdjq0/jb8g8ZcxFRsiSYI4e27K8ZqKoCJB1HAqG3t6KbWGQqNXPlZv2gqBLMngNPPgKc752V/7rnVQfjyOMZcYywCa1gF4kjg+J6/o3AFORAP/LQHy1ZdZ68bUQrydbZ1Y5yjFtp0ZczYNR6TVaKy6MOsOKMN1X8G+5HT9v5M=
  - secure: BVYzGrhR6z7DVmQv7EJ07c83ClemRRbzslMz1Sfw6hJFlIxXyOJ2doYKGv0jU7qbrD5g9qMQn22c00s2j9oC7hFaFMcxpASBD/kmpr7FSgeZ7sMAPQjkr/dSt2CG/NBj69IKLo0qwnfRYn0fdNc2kxL1UE4kWPvhmRDaN3vkfWrI6L8VQCMeM0xzz6nwXnIAgyxv4FNBavlFAgWF44pDY/s/MRy9x4ZPrKW2l15sQJTlWGXw0Rnek/SMd90dVTHR5vBlI8ywCdPSCrPgBI6ne9XzRhsKgWBsEdiHooHs0Q3AQDpdJoawN/tE3By57QTvNkYocMeVfbq8nsEs6i58lygXenZFF+RqVL44pm3WWJf9RSBtoZG0glA1fhXj7VnNxlNEcglZK6uvF+GaT5CHm72Vll/9qT9AdDNieXdnY3/g2mycIh8GPt8KmCW6aQClKKMQqbwm5fZ2tHI+VvWLCNlAecJVLrWKvUy6dhz3xbfXuMatN+F+sgrBigyDsawWH8CxJ2BbtKK/UNAU7vFMeQ9tQsstp9e8GnQvbMC4T3MmXLY8BP7LYRMQ11SijSBWs201FKxnTB3Rt/5keXvPlxL9iQNPjK6CApxcYUH4gnBRelnQz8jrcG2j43V5Kts/Xh9BxHEUabCgcZH+m8w6ooEhSchqbLO+qMLaqxrT7Gg=
  - secure: MavBwA/p+AZG/AtR85lzJloL0RnlQ3KkLtSvjPgMlpHSl1Rg5s4oubHQyRiYJTDShf7mA6mM4ESoJr+9t4JQ9gxYULfHbC+3HN+c/eA9PxhAYSj7JRKYQFVdodkL92L/Km/G75GPZhIO3ucNWxUEXLD8AnsIqIPev6VS7Dvrf5N9pH5/+XRkbsYdyIi4UyX7fueZaKnQy+E250ZZeMYAWvbmNq1V3H8PN5K/YBviQ1yBLIPMD4Uh3lxtNK81BdJ8maK508/Ksl1L2rLQ+J9gMqq4/bEixBp8D1NPYhf63pEtlYdmJWpkZZbMYraxl73g4Zs/NW5u7evxqFZouuHq42eFHxFbof5UdKE1/sUzzEZp9RYaVv/T3KW5OGMVNV5yXfFPPWZRb83jomDZaSc4Z1FRF/7gT/tWSvz7h2jtdwm4Qfyx7G5R7Qhl7q7W0mRGixKcNeSbErLZuRuUqWateCG6W1BEfWS2iYQQlHY5wmrKLYnP4qbMhoQMCXp8zsHdqyZAAtkNwue9UP658dPPdMV6+mn7Ii/mw+SKa0oQVSK0hpF2Qn+1TWzdUdWEytJAFtPUI2cnKUHBqtQe+2U6MK6YBBO0RllTFqqaY5C8VrmokUqkO1nGmLrnEVBZ/HkifdJ3+73DU2pwxomtN03YtivM11PdbAqfd5TmIsZ1G2Y=
  - secure: RNA8DXwuZo37DeM5YJV4X9IPweeW1CickGXuYBFi9vnSJknHHEGLUF8WnAAMa/3ExEjBRxnP+8xIrh4uHQCC1v6nnEPzNF8hU2LPTF59gABjIBwhyuM1+jgmIrrdtUoOJGmj2bSvXl7MnM2EwTTNC/J4bnW1YWp91oGHu0ADZrAYXc1Zd0PNZJwqF4pgpwSt3nJ0Ui2g8V1qTwbwraETG89bLiFQr3hEoN1jBcNLFYCSqrk0zymPQW96ThNmmVTKXwEQ9fTmpxvb92Y3qPt7Rc4Vbaaxm40KNIJP8qaHcJ/svc3OlAJ3NMZbIfncdew+rV9FPWOWA/L/BbCw9PSnbEvYX+S3e5GtDwQP4TD9gdBQjikWKFGateQdoHeCGHa/fX6kgOzALQDL3h8z8tSkycGjm6Rnpg6Eo3oZNbd/0iw1gqW6O7WK3XX7upVHrry45Kzid+Am5S1nYCqRiobZE/PuninjybZQVtsUh7jE7GsAjJdZ6EL0UAo0yrVcWPhUmZUFWjLK2IZR2Vw0g8FMw+O18p3SVz5NLkyuA0yLvLzFJqPy3GBSX3NPeSZwd9RkJPh1hRb2Xb/0K9+K0BQIzU8Dhuco3AFBCubzgQmgu+5HxRWBKV9fsDTuWhcsIpZXe9XS/SQCOf+rO5bzf+ZfbhvwFd2ekAcmiWomqrxyWQM=
scripts:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/docker_push.sh
- sh travis_scripts/deploy_aws.sh
