spring:
  application:
    name: infosys-gateway
  profiles:
    active:
    - default
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitive-headers: 
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
server:
  port: 5555