infosys-eureka:
    image: satriaprayoga/infosys-eureka:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8761:8761"

infosys-gateway:
    image: satriaprayoga/infosys-gateway:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "5555:5555"
    links: 
        - "infosys-eureka:infosys-eureka"
    environment: 
        PROFILE: "default"
        SERVER_PORT: "5555"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        RABBITMQ_PORT: "5672"

infosys-message:
    image: satriaprayoga/infosys-oauth:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8081:8081"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
        - "rabbitmq:rabbitmq"
    environment: 
        SERVER_PORT: "8081"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"
        RABBITMQ_URI: "rabbitmq"
        RABBITMQ_PORT: "5672"


infosys-oauth:
    image: satriaprayoga/infosys-oauth:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8082:8082"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
    environment: 
        SERVER_PORT: "8082"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"

infosys-destination:
    image: satriaprayoga/infosys-destination:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8083:8083"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
        - "infosys-oauth:infosys-oauth"
        - "rabbitmq:rabbitmq"
    environment: 
        SERVER_PORT: "8083"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"
        USERINFO_URI: "http://infosys-oauth:8082/user/"
        TOKENINFO_URI: "http://infosys-oauth:8082/oauth/check_token/"
        RABBITMQ_URI: "rabbitmq"
        RABBITMQ_PORT: "5672"

infosys-customer:
    image: satriaprayoga/infosys-customer:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8084:8084"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
        - "infosys-oauth:infosys-oauth"
        - "rabbitmq:rabbitmq"
    environment: 
        SERVER_PORT: "8084"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"
        USERINFO_URI: "http://infosys-oauth:8082/user/"
        TOKENINFO_URI: "http://infosys-oauth:8082/oauth/check_token/"
        RABBITMQ_URI: "rabbitmq"
        RABBITMQ_PORT: "5672"    
        
infosys-search:
    image: satriaprayoga/infosys-search:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports: 
        - "8085:8085"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
        - "infosys-oauth:infosys-oauth"
        - "rabbitmq:rabbitmq"
        - "elasticsearch:elasticsearch"
    environment: 
        SERVER_PORT: "8085"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"
        USERINFO_URI: "http://infosys-oauth:8082/user/"
        TOKENINFO_URI: "http://infosys-oauth:8082/oauth/check_token/"
        RABBITMQ_URI: "rabbitmq"
        RABBITMQ_PORT: "5672"    
        ELASTICSEARCH_URI: "elasticsearch"
        ELASTICSEARCH_PORT: "9200"

infosys-webclient:
    image: satriaprayoga/infosys-webclient:infosysApp-master-20200516234217-13
    mem_limit: 1073741824
    ports:
        - "9001:9001"
    links: 
        - "infosys-eureka:infosys-eureka"
        - "infosys-gateway:infosys-gateway"
        - "infosys-customer:infosys-customer"
        - "rabbitmq:rabbitmq"
    environment: 
        SERVER_PORT: "9001"
        EUREKASERVER_URI: "http://infosys-eureka:8761/eureka"
        EUREKASERVER_PORT: "8761"
        GATEWAYSERVER_PORT: "5555"
        
