server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8082/oauth/check_token/
      user-info-uri: http://localhost:8082/user/
      
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        tourEventOutput:
          destination: tourEvent
          content-type: application/json
        tourEventInput:
          destination: tourEvent
          content-type: application/json
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 
    url: jdbc:h2:mem:infosysdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
  application:
    name: backend-data
  servlet:
    multipart:
     enabled: true
     max-file-size: 100MB
     max-request-size: 1000MB


