server:
  port: 9090
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: infosys-webapp
  datasource:
    url: jdbc:h2:mem:tesdb
    driver-class-name: org.h2.Driver
    username: sa
    password:  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: gilsatpray@gmail.com
    password: Moscow2008
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    
    protocol: smtp
    test-connection: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 888294316119-2gtmkltk2r8o14n3p2ij1r1hjruj4dmn.apps.googleusercontent.com
            client-secret: TD69GIIyQBy1B48iM30WeGYE
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - profile
          
          
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
