server:
  port: 8089
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
            
spring:
  mail:
    host: smtp.mailtrap.io
    username: cc2b9138408642
    password: 0cb3a55f368c3a
    port: 2525
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        registrationEventInput:
          destination: registrationEvent
          content-type: application/json
        bookingEventInput:
          destination: bookingEvent
          content-type: application/json
  application:
    name: infosys-message
