spring: 
  application:
    name: infosys-oauth
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 
    url: jdbc:h2:mem:infosysdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    org.springframework.security: DEBUG
  
